export const mensagens: string[] = [
    'PROF:. Z NAO TERÀ AULA HOJE',
    'PROFESSOR X SALA L 307',
    'PROFESSOR Y SALA A 207',
    'SALA 300 INTEDITADA',
    'PROFESSOR A SALA F 307',
    'PROFESSOR N SALA G 407',
    'PROF:. C NAO TERÀ AULA HOJE',
    'PROFESSOR Q SALA A 307',
    'PROFESSOR H SALA B 307',
    'PROF:. K NAO TERÀ AULA HOJE',
]
